/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;
import cr.ac.una.fucem.inge.hawac.controller.AbonoController;
import cr.ac.una.fucem.inge.hawac.domain.Abono;
import cr.ac.una.fucem.inge.hawac.logic.Model;
import cr.ac.una.fucem.inge.hawac.model.AbonoModel;
import hawac.Application;
import java.util.Arrays;
import javax.swing.JOptionPane;


public class AbonoView extends javax.swing.JDialog implements java.util.Observer{

    
    AbonoModel model;
    AbonoController controller;
       
    public AbonoModel getModel() {
        return model;
    }

    public AbonoController getController() {
        return controller;
    }

    public void setModel(cr.ac.una.fucem.inge.hawac.model.AbonoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(cr.ac.una.fucem.inge.hawac.controller.AbonoController controller) {
        this.controller = controller;
    }
    
    public AbonoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //pack();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoBG = new javax.swing.ButtonGroup();
        inventarioBG = new javax.swing.ButtonGroup();
        dependienteLabel = new javax.swing.JLabel();
        realizadoLabel = new javax.swing.JLabel();
        dependienteText = new javax.swing.JTextField();
        fecha_realizadoText = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apartadoLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        apartadoText = new javax.swing.JTextField();
        montoText = new javax.swing.JTextField();
        saldoLabel1 = new javax.swing.JLabel();
        saldoText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABONO");

        dependienteLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dependienteLabel.setText("Dependiente");

        realizadoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        realizadoLabel.setText("Fecha Realizado");

        dependienteText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fecha_realizadoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha_realizadoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_realizadoTextActionPerformed(evt);
            }
        });

        AgregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/save2.png"))); // NOI18N
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/cancel.png"))); // NOI18N
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel1.setText("Guardar");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel2.setText("Salir");

        apartadoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        apartadoLabel.setText("Apartado");

        montoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        montoLabel.setText("Monto");

        apartadoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        apartadoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartadoTextActionPerformed(evt);
            }
        });

        montoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        montoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTextActionPerformed(evt);
            }
        });
        montoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoTextKeyTyped(evt);
            }
        });

        saldoLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        saldoLabel1.setText("Saldo");

        saldoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saldoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dependienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(montoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(apartadoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apartadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(realizadoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha_realizadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(dependienteText, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(saldoLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saldoText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dependienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dependienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apartadoLabel)
                            .addComponent(apartadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(realizadoLabel)
                            .addComponent(fecha_realizadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(montoLabel)
                            .addComponent(montoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoLabel1)
                            .addComponent(saldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
       controller.guardar();
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void fecha_realizadoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_realizadoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_realizadoTextActionPerformed

    private void apartadoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartadoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartadoTextActionPerformed

    private void montoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTextActionPerformed

    private void saldoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextActionPerformed

    private void montoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoTextKeyTyped

    }//GEN-LAST:event_montoTextKeyTyped

    private void montoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoTextKeyPressed

    }//GEN-LAST:event_montoTextKeyPressed

    private void montoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoTextKeyReleased
        if (montoText.getText().length() != 0) {
            try {
                if (Model.isNumeric(montoText.getText())) {
                    int abonoInt = Integer.parseInt(montoText.getText());
                    if(abonoInt>model.getCurrent().getA().getSaldo()){
                        saldoText.setText("Ha excedido el precio del producto.");
                    }else if(abonoInt<0){
                        saldoText.setText("Ha ingresado un número negativo.");
                    } else
                        saldoText.setText(model.getCurrent().getA().getSaldo() - abonoInt + "");
                } else if (Model.isNumeric2(montoText.getText())) {
                    double abono = Double.parseDouble(montoText.getText());
                    if(abono>model.getCurrent().getA().getSaldo()){
                        saldoText.setText("Ha excedido el precio del producto.");
                    }else if(abono<0){
                        saldoText.setText("Ha ingresado un número negativo.");
                    } else
                        saldoText.setText(model.getCurrent().getA().getSaldo() - abono + "");
                }else
                    saldoText.setText("Ha ingresado valores no numericos");
            } catch (Exception e) {
                saldoText.setText("Error");
            }
        }else{
            saldoText.setText(model.getCurrent().getA().getSaldo() + "");
        }
    }//GEN-LAST:event_montoTextKeyReleased

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {
        Abono current = model.getCurrent();
        //this.dependienteText.setEnabled(model.getModo() == Application.MODO_AGREGAR);
        
        current.setU(Application.USUARIO);
        if(current.getU() != null)
            current.setUsuario(Application.USUARIO.getIdUsuario());
        dependienteText.setEnabled(false);
        if(current.getU() != null)
            dependienteText.setText(current.getU().getNombre());
        else
            dependienteText.setText("");
        
        Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModo());
        
        this.fecha_realizadoText.setEnabled(false);
        this.fecha_realizadoText.setText(current.getFechaRealizado2());
        if (model.getErrores().get("Realizado") != null) {
            realizadoLabel.setBorder(Application.BORDER_ERROR);
            realizadoLabel.setToolTipText(model.getErrores().get("Realizado"));
        } else {
            realizadoLabel.setBorder(null);
            realizadoLabel.setToolTipText("");
        }
        
        this.apartadoText.setEnabled(false);
        this.apartadoText.setText(current.getA().getIdApartado()+"");
        if (model.getErrores().get("Producto") != null) {
            apartadoLabel.setBorder(Application.BORDER_ERROR);
            apartadoLabel.setToolTipText(model.getErrores().get("Producto"));
        } else {
            apartadoLabel.setBorder(null);
            apartadoLabel.setToolTipText("");
        }
        
        this.montoText.setText("");
        if (model.getErrores().get("Prima") != null) {
            montoLabel.setBorder(Application.BORDER_ERROR);
            montoLabel.setToolTipText(model.getErrores().get("Prima"));
        } else {
            montoLabel.setBorder(null);
            montoLabel.setToolTipText("");
        }
        
        saldoText.setEnabled(false);
        
        try{
            this.saldoText.setText(current.getA().getSaldo() + "");
        } catch (Exception e){
            this.saldoText.setText(e.toString());
        }
        
        AgregarButton.setVisible(editable);
        this.validate();
        if (!model.getMensaje().equals("")) {
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbonoView dialog = new AbonoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JButton ExitButton;
    public javax.swing.JLabel apartadoLabel;
    public javax.swing.JTextField apartadoText;
    private javax.swing.JLabel dependienteLabel;
    public javax.swing.JTextField dependienteText;
    public javax.swing.JTextField fecha_realizadoText;
    private javax.swing.ButtonGroup generoBG;
    private javax.swing.ButtonGroup inventarioBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel montoLabel;
    public javax.swing.JTextField montoText;
    public javax.swing.JLabel realizadoLabel;
    public javax.swing.JLabel saldoLabel1;
    public javax.swing.JTextField saldoText;
    // End of variables declaration//GEN-END:variables

}
