/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;
import cr.ac.una.fucem.inge.hawac.controller.ApartadoController;
import cr.ac.una.fucem.inge.hawac.controller.ProductoController;
import cr.ac.una.fucem.inge.hawac.domain.Apartado;
import cr.ac.una.fucem.inge.hawac.domain.Producto;
import cr.ac.una.fucem.inge.hawac.logic.Model;
import cr.ac.una.fucem.inge.hawac.model.ApartadoModel;
import cr.ac.una.fucem.inge.hawac.model.ProductoModel;
import hawac.Application;
import java.util.Arrays;
import javax.swing.JOptionPane;


public class ApartadoView extends javax.swing.JDialog implements java.util.Observer{

    
    ApartadoModel model;
    ApartadoController controller;
       
    public ApartadoModel getModel() {
        return model;
    }

    public ApartadoController getController() {
        return controller;
    }

    public void setModel(cr.ac.una.fucem.inge.hawac.model.ApartadoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(cr.ac.una.fucem.inge.hawac.controller.ApartadoController controller) {
        this.controller = controller;
    }
    
    public ApartadoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pack();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoBG = new javax.swing.ButtonGroup();
        inventarioBG = new javax.swing.ButtonGroup();
        clienteLabel = new javax.swing.JLabel();
        dependienteLabel = new javax.swing.JLabel();
        realizadoLabel = new javax.swing.JLabel();
        dependienteText = new javax.swing.JTextField();
        clienteText = new javax.swing.JTextField();
        fecha_realizadoText = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        limiteLabel = new javax.swing.JLabel();
        fecha_limiteText = new javax.swing.JTextField();
        productoLabel = new javax.swing.JLabel();
        primaLabel = new javax.swing.JLabel();
        productoText = new javax.swing.JTextField();
        primaText = new javax.swing.JTextField();
        saldoLabel1 = new javax.swing.JLabel();
        saldoText = new javax.swing.JTextField();
        buscar_clienteB = new javax.swing.JButton();
        buscar_productoB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(387, 400));

        clienteLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        clienteLabel.setText("Cliente");

        dependienteLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dependienteLabel.setText("Dependiente");

        realizadoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        realizadoLabel.setText("Fecha Realizado");

        dependienteText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clienteText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fecha_realizadoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha_realizadoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_realizadoTextActionPerformed(evt);
            }
        });

        AgregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/save2.png"))); // NOI18N
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/cancel.png"))); // NOI18N
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel1.setText("Guardar");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel2.setText("Salir");

        limiteLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        limiteLabel.setText("Fecha Límite");

        fecha_limiteText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha_limiteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_limiteTextActionPerformed(evt);
            }
        });

        productoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        productoLabel.setText("Producto");

        primaLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        primaLabel.setText("Prima");

        productoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoTextActionPerformed(evt);
            }
        });

        primaText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        primaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primaTextActionPerformed(evt);
            }
        });
        primaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                primaTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primaTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                primaTextKeyTyped(evt);
            }
        });

        saldoLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        saldoLabel1.setText("Saldo");

        saldoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saldoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextActionPerformed(evt);
            }
        });

        buscar_clienteB.setText("Buscar");
        buscar_clienteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_clienteBActionPerformed(evt);
            }
        });

        buscar_productoB.setText("Buscar");
        buscar_productoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_productoBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(realizadoLabel)
                            .addComponent(productoLabel)
                            .addComponent(limiteLabel)
                            .addComponent(primaLabel)
                            .addComponent(saldoLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dependienteText, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(fecha_limiteText, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(fecha_realizadoText)
                            .addComponent(clienteText)
                            .addComponent(productoText, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(primaText)
                            .addComponent(saldoText, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscar_clienteB)
                            .addComponent(buscar_productoB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dependienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dependienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dependienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(clienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_clienteB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizadoLabel)
                    .addComponent(fecha_realizadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteLabel)
                    .addComponent(fecha_limiteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productoLabel)
                    .addComponent(productoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_productoB))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaLabel)
                    .addComponent(primaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoLabel1)
                    .addComponent(saldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
       controller.guardar();
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void fecha_limiteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_limiteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_limiteTextActionPerformed

    private void fecha_realizadoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_realizadoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_realizadoTextActionPerformed

    private void productoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoTextActionPerformed

    private void primaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primaTextActionPerformed

    private void saldoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextActionPerformed

    private void buscar_clienteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_clienteBActionPerformed
        this.setVisible(false);
        controller.preAgregarCliente();
    }//GEN-LAST:event_buscar_clienteBActionPerformed

    private void buscar_productoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_productoBActionPerformed
        this.setVisible(false);
        controller.preAgregarProducto();
    }//GEN-LAST:event_buscar_productoBActionPerformed

    private void primaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primaTextKeyTyped

    }//GEN-LAST:event_primaTextKeyTyped

    private void primaTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primaTextKeyPressed

    }//GEN-LAST:event_primaTextKeyPressed

    private void primaTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primaTextKeyReleased
        if (primaText.getText().length() != 0) {
            try {
                if (Model.isNumeric(primaText.getText())) {
                    int abonoInt = Integer.parseInt(primaText.getText());
                    if(abonoInt>model.getCurrent().getP().getPrecio()){
                        saldoText.setText("Ha excedido el precio del producto.");
                    }else if(abonoInt<0){
                        saldoText.setText("Ha ingresado un número negativo.");
                    } else
                        saldoText.setText(model.getCurrent().getP().getPrecio() - abonoInt + "");
                } else if (Model.isNumeric2(primaText.getText())) {
                    double abono = Double.parseDouble(primaText.getText());
                    if(abono>model.getCurrent().getP().getPrecio()){
                        saldoText.setText("Ha excedido el precio del producto.");
                    }else if(abono<0){
                        saldoText.setText("Ha ingresado un número negativo.");
                    } else
                        saldoText.setText(model.getCurrent().getP().getPrecio() - abono + "");
                }else
                    saldoText.setText("Ha ingresado valores no numericos");
            } catch (Exception e) {
                saldoText.setText("Error");
            }
        }else{
            saldoText.setText(model.getCurrent().getP().getPrecio() + "");
        }
    }//GEN-LAST:event_primaTextKeyReleased

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {
        Apartado current = model.getCurrent();
        //this.dependienteText.setEnabled(model.getModo() == Application.MODO_AGREGAR);
        
        current.setU(Application.USUARIO);
        if(current.getU() != null)
            current.setUsuario(Application.USUARIO.getIdUsuario());
        dependienteText.setEnabled(false);
        if(current.getU() != null)
            dependienteText.setText(current.getU().getNombre());
        else
            dependienteText.setText("");
        clienteText.setEnabled(false);
        
        
        if(current.getC().getNombre().length()==0)
            this.clienteText.setText("");
        else
            this.clienteText.setText(current.getC().getNombre());
        if (model.getErrores().get("Cliente") != null) {
            clienteLabel.setBorder(Application.BORDER_ERROR);
            clienteLabel.setToolTipText(model.getErrores().get("Cliente"));
        } else {
            clienteLabel.setBorder(null);
            clienteLabel.setToolTipText("");
        }
        
        Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModo());
        
        
        this.fecha_limiteText.setEnabled(false);
        this.fecha_limiteText.setText(current.getFechaLimite2());
        if (model.getErrores().get("Limite") != null) {
            limiteLabel.setBorder(Application.BORDER_ERROR);
            limiteLabel.setToolTipText(model.getErrores().get("Limite"));
        } else {
            limiteLabel.setBorder(null);
            limiteLabel.setToolTipText("");
        }
        
        this.fecha_realizadoText.setEnabled(false);
        this.fecha_realizadoText.setText(current.getFechaRealizado2());
        if (model.getErrores().get("Realizado") != null) {
            realizadoLabel.setBorder(Application.BORDER_ERROR);
            realizadoLabel.setToolTipText(model.getErrores().get("Realizado"));
        } else {
            realizadoLabel.setBorder(null);
            realizadoLabel.setToolTipText("");
        }
        
        this.productoText.setEnabled(false);
        this.productoText.setText(current.getP().getDescripcion());
        if (model.getErrores().get("Producto") != null) {
            productoLabel.setBorder(Application.BORDER_ERROR);
            productoLabel.setToolTipText(model.getErrores().get("Producto"));
        } else {
            productoLabel.setBorder(null);
            productoLabel.setToolTipText("");
        }
        
        this.primaText.setText("");
        if (model.getErrores().get("Prima") != null) {
            primaLabel.setBorder(Application.BORDER_ERROR);
            primaLabel.setToolTipText(model.getErrores().get("Prima"));
        } else {
            primaLabel.setBorder(null);
            primaLabel.setToolTipText("");
        }
        
        saldoText.setEnabled(false);
        
        try{
            this.saldoText.setText(current.getP().getPrecio() + "");
        } catch (Exception e){
            this.saldoText.setText(e.toString());
        }
        
        AgregarButton.setVisible(editable);
        this.validate();
        if (!model.getMensaje().equals("")) {
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApartadoView dialog = new ApartadoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton buscar_clienteB;
    private javax.swing.JButton buscar_productoB;
    private javax.swing.JLabel clienteLabel;
    public javax.swing.JTextField clienteText;
    private javax.swing.JLabel dependienteLabel;
    public javax.swing.JTextField dependienteText;
    public javax.swing.JTextField fecha_limiteText;
    public javax.swing.JTextField fecha_realizadoText;
    private javax.swing.ButtonGroup generoBG;
    private javax.swing.ButtonGroup inventarioBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel limiteLabel;
    public javax.swing.JLabel primaLabel;
    public javax.swing.JTextField primaText;
    public javax.swing.JLabel productoLabel;
    public javax.swing.JTextField productoText;
    public javax.swing.JLabel realizadoLabel;
    public javax.swing.JLabel saldoLabel1;
    public javax.swing.JTextField saldoText;
    // End of variables declaration//GEN-END:variables

}
