/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;

import cr.ac.una.fucem.inge.hawac.controller.BitacorasController;
import cr.ac.una.fucem.inge.hawac.model.BitacorasModel;
import hawac.Application;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BitacorasView extends javax.swing.JInternalFrame implements java.util.Observer {

    BitacorasController controller;
    BitacorasModel model;
    DefaultTableModel productos;

    public BitacorasController getController() {
        return controller;
    }

    public BitacorasModel getModel() {
        return model;
    }

    public void setController(BitacorasController controller) {
        this.controller = controller;
    }

    public void setModel(BitacorasModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public DefaultTableModel getBitacoras() {
        return productos;
    }

    public void setBitacoras(DefaultTableModel productos) {
        this.productos = productos;
        model.addObserver(this);
    }

    public BitacorasView() {
        super("", false, true);
        initComponents();
    }

    /**
     * Creates new form BitacorasView
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Busqueda = new javax.swing.ButtonGroup();
        DescripcionText = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        ProductosScrollPane = new javax.swing.JScrollPane();
        CatalogoTable = new javax.swing.JTable();
        usuarioRB = new javax.swing.JRadioButton();
        buscarLb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        descripcionRB = new javax.swing.JRadioButton();
        fechaC = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("BITACORAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DescripcionText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(DescripcionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 157, -1));

        BuscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/search2.png"))); // NOI18N
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 36, 36));

        ProductosScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosScrollPaneMouseClicked(evt);
            }
        });

        CatalogoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CatalogoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalogoTableMouseClicked(evt);
            }
        });
        ProductosScrollPane.setViewportView(CatalogoTable);

        getContentPane().add(ProductosScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 402));

        Busqueda.add(usuarioRB);
        usuarioRB.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        usuarioRB.setText("Usuario");
        getContentPane().add(usuarioRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        buscarLb.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        buscarLb.setText("Seleccione el argumento a buscar");
        getContentPane().add(buscarLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setText("Ver Todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 30));

        Busqueda.add(descripcionRB);
        descripcionRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descripcionRB.setText("Descripcion");
        getContentPane().add(descripcionRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        getContentPane().add(fechaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jButton2.setText("Buscar Por Fecha");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        if (false && usuarioRB.isSelected() == false && descripcionRB.isSelected() == false) {
            buscarLb.setBorder(Application.BORDER_ERROR);
            buscarLb.setToolTipText(model.getErrores().get("DescripcionText"));
        } else {
            buscarLb.setBorder(null);
            buscarLb.setToolTipText("");
            if (descripcionRB.isSelected() == true && DescripcionText.getText().length() == 0) {
                model.getErrores().put("DescripcionText", "Digite la descripcion a buscar");
                buscarLb.setBorder(Application.BORDER_ERROR);
                buscarLb.setToolTipText(model.getErrores().get("DescripcionText"));
            }
            if (descripcionRB.isSelected() == true && DescripcionText.getText().length() != 0) {
                controller.buscarPorDescripcion();
            }
            if (usuarioRB.isSelected() == true && DescripcionText.getText().length() == 0) {
                model.getErrores().put("DescripcionText", "Digite la descripcion a buscar");
                buscarLb.setBorder(Application.BORDER_ERROR);
                buscarLb.setToolTipText(model.getErrores().get("DescripcionText"));
            }
            if (usuarioRB.isSelected() == true && DescripcionText.getText().length() != 0) {
                controller.buscarPorUsuario();
            }
        }
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void ProductosScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosScrollPaneMouseClicked

    }//GEN-LAST:event_ProductosScrollPaneMouseClicked

    private void CatalogoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatalogoTableMouseClicked

    }//GEN-LAST:event_CatalogoTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.buscar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date a = fechaC.getDate();
        if(a!=null){
            controller.buscarPorFecha(a);
        }
        else
            fechaC.setBorder(Application.BORDER_ERROR);
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {
        DescripcionText.setText(model.getFilter().getDescripcion());
        if (model.getErrores().get("DescripcionText") != null) {
            buscarLb.setBorder(Application.BORDER_ERROR);
            buscarLb.setToolTipText(model.getErrores().get("DescripcionText"));
        } else {
            buscarLb.setBorder(null);
            buscarLb.setToolTipText("");
        }

        CatalogoTable.setModel(model.getBitacoras());
        this.revalidate();
        if (!model.getMensaje().equals("")) {
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoView dialog = new ProductoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarButton;
    private javax.swing.ButtonGroup Busqueda;
    public javax.swing.JTable CatalogoTable;
    public javax.swing.JTextField DescripcionText;
    private javax.swing.JScrollPane ProductosScrollPane;
    private javax.swing.JLabel buscarLb;
    private javax.swing.JRadioButton descripcionRB;
    private com.toedter.calendar.JDateChooser fechaC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JRadioButton usuarioRB;
    // End of variables declaration//GEN-END:variables

}
