/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;
/*import ferreteria.Application;
import ferreteriaentidades.Efectivo;
import ferreteria.presentacion.controller.EfectivoController;
import ferreteria.presentacion.controller.FacturasVentasController;
import ferreteria.presentacion.model.EfectivoModel;
*/
import cr.ac.una.fucem.inge.hawac.controller.EfectivoController;
import cr.ac.una.fucem.inge.hawac.model.EfectivoModel;
import javax.swing.JOptionPane;


public class EfectivoView extends javax.swing.JDialog implements java.util.Observer{

    EfectivoModel model;
    EfectivoController controller;
    
    /**
     * Creates new form EfectivoView
     * @param parent
     * @param modal
     */
    public EfectivoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
        public EfectivoModel getModel() {
        return model;
    }

    public EfectivoController getController() {
        return controller;
    }

    public void setModel(cr.ac.una.fucem.inge.hawac.model.EfectivoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(cr.ac.una.fucem.inge.hawac.controller.EfectivoController controller) {
        this.controller = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EfectivoTittle = new javax.swing.JLabel();
        MontoLabel = new javax.swing.JLabel();
        VueltoLabel = new javax.swing.JLabel();
        Monto = new javax.swing.JTextField();
        Vuelto = new javax.swing.JTextField();
        PagarButton = new javax.swing.JButton();
        PagarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EfectivoTittle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EfectivoTittle.setText("Efectivo");

        MontoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        MontoLabel.setText("Monto");

        VueltoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        VueltoLabel.setText("Vuelto");

        Monto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });

        Vuelto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Vuelto.setEnabled(false);
        Vuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VueltoActionPerformed(evt);
            }
        });

        PagarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/pagar.png"))); // NOI18N
        PagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarButtonActionPerformed(evt);
            }
        });

        PagarLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        PagarLabel.setText("Pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MontoLabel)
                    .addComponent(VueltoLabel))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Monto)
                    .addComponent(Vuelto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PagarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(EfectivoTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EfectivoTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MontoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VueltoLabel))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PagarLabel)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarButtonActionPerformed

            controller.registrarPago();
    }//GEN-LAST:event_PagarButtonActionPerformed

    private void VueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VueltoActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EfectivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EfectivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EfectivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EfectivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EfectivoView dialog = new EfectivoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EfectivoTittle;
    public javax.swing.JTextField Monto;
    private javax.swing.JLabel MontoLabel;
    private javax.swing.JButton PagarButton;
    private javax.swing.JLabel PagarLabel;
    public javax.swing.JTextField Vuelto;
    private javax.swing.JLabel VueltoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
        public void update(java.util.Observable updatedModel,Object parametros) {
        /*Efectivo current = model.getCurrent();
        String ex = String.valueOf(current.getMonto());
        Monto.setText(ex);
         if (model.getErrores().get("Monto")!=null){
            MontoLabel.setBorder(Application.BORDER_ERROR);
            MontoLabel.setToolTipText(model.getErrores().get("Monto"));
         }
         else{
            MontoLabel.setBorder(null);
            MontoLabel.setToolTipText("");
          }
        String nv = String.valueOf(current.getVuelto());
        Vuelto.setText(nv);
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
                */
    }
}
