/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;
import cr.ac.una.fucem.inge.hawac.controller.FacturasPagadasController;
import cr.ac.una.fucem.inge.hawac.logic.Model;
import cr.ac.una.fucem.inge.hawac.model.FacturasPagadasModel;
import hawac.Application;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class FacturasPagadasView extends javax.swing.JInternalFrame implements java.util.Observer {

    FacturasPagadasController controller;
    FacturasPagadasModel model;
    
    public FacturasPagadasView() {
         super("",false,true);
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreLb = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numeroRB = new javax.swing.JRadioButton();
        clienteRB = new javax.swing.JRadioButton();
        vendedorRB = new javax.swing.JRadioButton();
        buscarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("FACTURAS PAGADAS");

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFacturas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("FACTURAS");

        nombreLb.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nombreLb.setText("Busqueda por:");

        nombreTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        buscarButton.setText("Ver Todo");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                                                     FACTURAS PAGADAS");
        jLabel2.setOpaque(true);

        busquedaBG.add(numeroRB);
        numeroRB.setText("Numero");

        busquedaBG.add(clienteRB);
        clienteRB.setText("Cliente");

        busquedaBG.add(vendedorRB);
        vendedorRB.setText("Vendedor");

        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/fucem/inge/hawac/view/icons/search2.png"))); // NOI18N
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeroRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendedorRB))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreLb)
                                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroRB)
                                    .addComponent(clienteRB)
                                    .addComponent(vendedorRB)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
       controller.buscar();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        if(clienteRB.isSelected()==false && numeroRB.isSelected()==false && vendedorRB.isSelected()==false){
            nombreLb.setBorder(Application.BORDER_ERROR);
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun criterio de Busqueda");
        }else{
            if(clienteRB.isSelected() && nombreTF.getText().length()!=0){
                controller.buscarPorCliente();
                return;
            }
            if(numeroRB.isSelected() && nombreTF.getText().length()!=0 && Model.isNumeric(nombreTF.getText())){
                controller.buscarPorNumero();
                return;
            }
            if(vendedorRB.isSelected()&& nombreTF.getText().length()!=0){
                controller.buscarPorVendedor();
                return;
            }
            if(clienteRB.isSelected() && nombreTF.getText().length()==0){
                nombreLb.setBorder(Application.BORDER_ERROR);
                JOptionPane.showMessageDialog(this, "No ha ingresado ningun texto");
            }
            if(numeroRB.isSelected() && nombreTF.getText().length()==0){
                nombreLb.setBorder(Application.BORDER_ERROR);
                JOptionPane.showMessageDialog(this, "No ha ingresado ningun texto");
            }else if(numeroRB.isSelected() && !Model.isNumeric(nombreTF.getText())){
                nombreLb.setBorder(Application.BORDER_ERROR);
                JOptionPane.showMessageDialog(this, "Por favor ingrese solo valores numericos");
            }
            if(vendedorRB.isSelected()&& nombreTF.getText().length()==0){
                nombreLb.setBorder(Application.BORDER_ERROR);
                JOptionPane.showMessageDialog(this, "No ha ingresado ningun texto");
            }
        }
    }//GEN-LAST:event_buscarBActionPerformed

    public FacturasPagadasController getController() {
        return controller;
    }

    public FacturasPagadasModel getModel() {
        return model;
    }

    public void setController(FacturasPagadasController controller) {
        this.controller = controller;
    }

    public void setModel(FacturasPagadasModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
   @Override
    public void update(java.util.Observable updatedModel,Object parametros) {
        if(model.getErrores().get("nombreTextFd")!= null){
            nombreLb.setBorder(Application.BORDER_ERROR);
            nombreLb.setToolTipText(model.getErrores().get("nombreTextFd"));
        }else{
            nombreLb.setBorder(null);
            nombreLb.setToolTipText("");
        }
        tablaFacturas.setModel(model.getFacturas());
        this.revalidate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
        tablaFacturas.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        tablaFacturas.getColumnModel().getColumn(0).setPreferredWidth(20);
        tablaFacturas.getColumnModel().getColumn(1).setPreferredWidth(40);
        tablaFacturas.getColumnModel().getColumn(2).setPreferredWidth(40);
        tablaFacturas.getColumnModel().getColumn(3).setPreferredWidth(50);
        tablaFacturas.getColumnModel().getColumn(4).setPreferredWidth(30); 
    } 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FacturasPagadasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarB;
    public javax.swing.JButton buscarButton;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JRadioButton clienteRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel nombreLb;
    public javax.swing.JTextField nombreTF;
    private javax.swing.JRadioButton numeroRB;
    public javax.swing.JTable tablaFacturas;
    private javax.swing.JRadioButton vendedorRB;
    // End of variables declaration//GEN-END:variables
}
