/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.fucem.inge.hawac.view;
/*import ferreteria.Application;
import ferreteria.presentacion.controller.FacturasVentasController;
import ferreteriaentidades.TarjetaCredito;
import ferreteria.presentacion.controller.TarjetaCreditoController;
import ferreteria.presentacion.model.TarjetaCreditoModel;*/
import java.util.Observable;
import javax.swing.JOptionPane;


public class TarjetaCreditoView extends javax.swing.JDialog implements java.util.Observer{
 
//    TarjetaCreditoModel model;
//    TarjetaCreditoController controller;
    
    /**
     * Creates new form TarjetaCreditoView
     * @param parent
     * @param modal
     */
    public TarjetaCreditoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /*
    public TarjetaCreditoModel getModel() {
        return model;
    }

    public TarjetaCreditoController getController() {
        return controller;
    }

    public void setModel(ferreteria.presentacion.model.TarjetaCreditoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(ferreteria.presentacion.controller.TarjetaCreditoController controller) {
        this.controller = controller;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tittle = new javax.swing.JLabel();
        MontoLabel = new javax.swing.JLabel();
        VoucherLabel = new javax.swing.JLabel();
        Monto = new javax.swing.JTextField();
        Voucher = new javax.swing.JTextField();
        pagarbutton = new javax.swing.JButton();
        PagarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tittle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Tittle.setText("Tarjeta de credito");

        MontoLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        MontoLabel.setText("Monto");

        VoucherLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        VoucherLabel.setText("Voucher");

        Monto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });

        Voucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoucherActionPerformed(evt);
            }
        });

        pagarbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/ferreteria/presentacion/view/icons/pagar.png"))); // NOI18N
        pagarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarbuttonActionPerformed(evt);
            }
        });

        PagarLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        PagarLabel.setText(" Pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tittle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoucherLabel)
                            .addComponent(MontoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Voucher, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(Monto))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PagarLabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Tittle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoucherLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MontoLabel)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Monto))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PagarLabel)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarbuttonActionPerformed
       // controller.registrarPago();
    }//GEN-LAST:event_pagarbuttonActionPerformed

    private void VoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoucherActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarjetaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarjetaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarjetaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarjetaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TarjetaCreditoView dialog = new TarjetaCreditoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Monto;
    private javax.swing.JLabel MontoLabel;
    private javax.swing.JLabel PagarLabel;
    private javax.swing.JLabel Tittle;
    public javax.swing.JTextField Voucher;
    private javax.swing.JLabel VoucherLabel;
    private javax.swing.JButton pagarbutton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable updatedModel,Object parametros) {
     /*   TarjetaCredito current = model.getCurrent();
        String ex = String.valueOf(current.getMonto());
        Monto.setText(ex);
         if (model.getErrores().get("Monto")!=null){
            MontoLabel.setBorder(Application.BORDER_ERROR);
            MontoLabel.setToolTipText(model.getErrores().get("Monto"));
         }
         else{
            MontoLabel.setBorder(null);
            MontoLabel.setToolTipText("");
          }
        String nv = String.valueOf(current.getNumeroVoucher());
        Voucher.setText(nv);
        if(model.getErrores().get("Voucher")!= null){
            VoucherLabel.setBorder(Application.BORDER_ERROR);
            VoucherLabel.setToolTipText(model.getErrores().get("Voucher"));
        }else{
            VoucherLabel.setBorder(null);
            VoucherLabel.setToolTipText("");
        }
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
             */
    }
}
