package cr.ac.una.fucem.inge.hawac.domain;
// Generated 30-mar-2017 21:01:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Abono generated by hbm2java
 */
public class Abono  implements java.io.Serializable {


     private Integer idAbonos;
     private Apartado apartado;
     private Date fechaRealizado;
     private float monto;
     private double saldo;

    public Abono() {
    }

	
    public Abono(Date fechaRealizado, float monto, double saldo) {
        this.fechaRealizado = fechaRealizado;
        this.monto = monto;
        this.saldo = saldo;
    }
    public Abono(Apartado apartado, Date fechaRealizado, float monto, double saldo) {
       this.apartado = apartado;
       this.fechaRealizado = fechaRealizado;
       this.monto = monto;
       this.saldo = saldo;
    }
   
    public Integer getIdAbonos() {
        return this.idAbonos;
    }
    
    public void setIdAbonos(Integer idAbonos) {
        this.idAbonos = idAbonos;
    }
    public Apartado getApartado() {
        return this.apartado;
    }
    
    public void setApartado(Apartado apartado) {
        this.apartado = apartado;
    }
    public Date getFechaRealizado() {
        return this.fechaRealizado;
    }
    
    public void setFechaRealizado(Date fechaRealizado) {
        this.fechaRealizado = fechaRealizado;
    }
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    public double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }




}


