package cr.ac.una.fucem.inge.hawac.domain;
// Generated 05-mar-2017 20:19:45 by Hibernate Tools 4.3.1



/**
 * Apartadoproducto generated by hbm2java
 */
public class Apartadoproducto  implements java.io.Serializable {


     private ApartadoproductoId id;
     private Apartado apartado;
     private Producto producto;
     private int cantidad;

    public Apartadoproducto() {
    }

    public Apartadoproducto(ApartadoproductoId id, Apartado apartado, Producto producto, int cantidad) {
       this.id = id;
       this.apartado = apartado;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public ApartadoproductoId getId() {
        return this.id;
    }
    
    public void setId(ApartadoproductoId id) {
        this.id = id;
    }
    public Apartado getApartado() {
        return this.apartado;
    }
    
    public void setApartado(Apartado apartado) {
        this.apartado = apartado;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


