package cr.ac.una.fucem.inge.hawac.domain;
// Generated 27-feb-2017 0:13:16 by Hibernate Tools 4.3.1



/**
 * ApartadoproductoId generated by hbm2java
 */
public class ApartadoproductoId  implements java.io.Serializable {


     private int producto;
     private int apartado;

    public ApartadoproductoId() {
    }

    public ApartadoproductoId(int producto, int apartado) {
       this.producto = producto;
       this.apartado = apartado;
    }
   
    public int getProducto() {
        return this.producto;
    }
    
    public void setProducto(int producto) {
        this.producto = producto;
    }
    public int getApartado() {
        return this.apartado;
    }
    
    public void setApartado(int apartado) {
        this.apartado = apartado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ApartadoproductoId) ) return false;
		 ApartadoproductoId castOther = ( ApartadoproductoId ) other; 
         
		 return (this.getProducto()==castOther.getProducto())
 && (this.getApartado()==castOther.getApartado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProducto();
         result = 37 * result + this.getApartado();
         return result;
   }   


}


