package cr.ac.una.fucem.inge.hawac.domain;
// Generated 05-mar-2017 20:19:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private int entrada;
     private Usuario usuario;
     private String descripcion;
     private Date fecha;

    public Bitacora() {
    }

    public Bitacora(int entrada, Usuario usuario, String descripcion, Date fecha) {
       this.entrada = entrada;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public int getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(int entrada) {
        this.entrada = entrada;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


