package cr.ac.una.fucem.inge.hawac.domain;
// Generated 26-feb-2017 17:35:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private float totalComprado;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Apartado> apartados = new HashSet<Apartado>(0);

    public Cliente() {
    }

	
    public Cliente(int cedula, String nombre, float totalComprado) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.totalComprado = totalComprado;
    }
    public Cliente(int cedula, String nombre, float totalComprado, Set<Factura> facturas, Set<Apartado> apartados) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.totalComprado = totalComprado;
       this.facturas = facturas;
       this.apartados = apartados;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getTotalComprado() {
        return this.totalComprado;
    }
    
    public void setTotalComprado(float totalComprado) {
        this.totalComprado = totalComprado;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Apartado> getApartados() {
        return this.apartados;
    }
    
    public void setApartados(Set<Apartado> apartados) {
        this.apartados = apartados;
    }




}


