package cr.ac.una.fucem.inge.hawac.domain;
// Generated 24-mar-2017 14:24:28 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int codigoFactura;
     private Apartado apartado;
     private int cliente;
     private int usuario;
     private float monto;
     private Date fecha;
     private Set<Linea> lineas = new HashSet<Linea>(0);
     private Cliente c;
     private Usuario u;

    public Factura() {
        codigoFactura = 0;
        cliente = 0;
        usuario = 0;
        monto = 0;
        fecha = new Date();
        c = new Cliente();
        u = new Usuario();
    }

	
    public Factura(int codigoFactura, float monto, Date fecha) {
        this.codigoFactura = codigoFactura;
        this.monto = monto;
        this.fecha = fecha;
    }
    public Factura(int codigoFactura, Apartado apartado, int cliente, int usuario, float monto, Date fecha, Set<Linea> lineas) {
       this.codigoFactura = codigoFactura;
       this.apartado = apartado;
       this.cliente = cliente;
       this.usuario = usuario;
       this.monto = monto;
       this.fecha = fecha;
       this.lineas = lineas;
    }
   
    public int getCodigoFactura() {
        return this.codigoFactura;
    }
    
    public void setCodigoFactura(int codigoFactura) {
        this.codigoFactura = codigoFactura;
    }
    public Apartado getApartado() {
        return this.apartado;
    }
    
    public void setApartado(Apartado apartado) {
        this.apartado = apartado;
    }
    public int getCliente() {
        return this.cliente;
    }
    
    public void setCliente(int cliente) {
        this.cliente = cliente;
    }
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Linea> getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set<Linea> lineas) {
        this.lineas = lineas;
    }
    
    public String getFechaActual(){
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }
    
    public String getFechaActual2(){
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY-MM-dd");
        return formatoFecha.format(fecha);
    }

    public Cliente getC() {
        return c;
    }

    public void setC(Cliente c) {
        this.c = c;
    }

    public Usuario getU() {
        return u;
    }

    public void setU(Usuario u) {
        this.u = u;
    }
    
    public String getHoraActual(){
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        return formatoHora.format(fecha);
    }
}