package cr.ac.una.fucem.inge.hawac.domain;
// Generated 27-feb-2017 0:13:16 by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private InventarioId id;
     private Producto producto;
     private int cantidad;

    public Inventario() {
    }

    public Inventario(InventarioId id, Producto producto, int cantidad) {
       this.id = id;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public InventarioId getId() {
        return this.id;
    }
    
    public void setId(InventarioId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


