package cr.ac.una.fucem.inge.hawac.domain;
// Generated 24-mar-2017 14:24:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java y a4e3g6o0
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String password;
     private int tipo;
     private String nombre;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

    public Usuario() {
        idUsuario = 0;
        tipo = -1;
        password = "";
        nombre = "";
    }

	
    public Usuario(int idUsuario, String password, int tipo, String nombre) {
        this.idUsuario = idUsuario;
        this.password = password;
        this.tipo = tipo;
        this.nombre = nombre;
    }
    public Usuario(int idUsuario, String password, int tipo, String nombre, Set<Factura> facturas, Set<Bitacora> bitacoras) {
       this.idUsuario = idUsuario;
       this.password = password;
       this.tipo = tipo;
       this.nombre = nombre;
       this.facturas = facturas;
       this.bitacoras = bitacoras;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }
    
    public int tipo(){
        return this.tipo;
    }


}


